CREATE TABLE AppUser (
    ID SERIAL PRIMARY KEY,
    NAME TEXT UNIQUE,
    ROLE TEXT,
    AGE INTEGER,
    STATE TEXT
);

CREATE TABLE ShoppingCart (
    ID SERIAL PRIMARY KEY,
    OWNER INTEGER REFERENCES AppUser(ID) NOT NULL
);

CREATE TABLE PurchaseOrder (
    ID SERIAL PRIMARY KEY,
    CHECKOUT_ID INTEGER REFERENCES ShoppingCart(ID) NOT NULL
);

CREATE TABLE PRODUCT (
    ID SERIAL PRIMARY KEY,
    NAME TEXT,
    SKU TEXT UNIQUE,
    PRICE REAL,
    CATEGORY_ID INTEGER REFERENCES Category(ID) NOT NULL
);

CREATE TABLE CATEGORY (
    ID SERIAL PRIMARY KEY,
    NAME TEXT UNIQUE,
    DESCRIPTION TEXT
);

CREATE TABLE CONTAINS (
    ID SERIAL PRIMARY KEY,
    ADDED_PRICE REAL,
    ADDED_TIME TIME,
    QUANTITY INTEGER,
    PRODUCT_ID INTEGER REFERENCES Product(ID),
    CART_ID INTEGER REFERENCES ShoppingCart(ID)
);
